/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.UFSC.INE5608.projetoDiaristas.Telas;

/**
 *
 * @author Ismael
 */
public class TelaCadastroDiarista extends javax.swing.JFrame {
    private static TelaCadastroDiarista instancia;
    public static TelaCadastroDiarista getInstance() {
        if(instancia == null){
            instancia = new TelaCadastroDiarista();
        }
        return instancia;
    }
    /**
     * Creates new form TelaCadastroDiarista
     */
    private TelaCadastroDiarista() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDiarista = new javax.swing.JPanel();
        txtNome = new javax.swing.JLabel();
        txtPDF = new javax.swing.JLabel();
        txtRG = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtHasContaCadastrada = new javax.swing.JLabel();
        campoObservacoes = new javax.swing.JTextField();
        txtObservacoes = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        campoRG = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        campoCPF = new javax.swing.JTextField();
        painelInformacoes = new javax.swing.JPanel();
        txtValorDiaria = new javax.swing.JLabel();
        comboValor = new javax.swing.JComboBox<>();
        painelDias = new javax.swing.JPanel();
        checkSegunda = new javax.swing.JCheckBox();
        checkTerca = new javax.swing.JCheckBox();
        checkQuarta = new javax.swing.JCheckBox();
        checkQuinta = new javax.swing.JCheckBox();
        checkSexta = new javax.swing.JCheckBox();
        checkSabado = new javax.swing.JCheckBox();
        checkDomingo = new javax.swing.JCheckBox();
        botaoCadastrar = new javax.swing.JButton();
        txtCamposObrigatorios = new javax.swing.JLabel();
        botaoCancelar = new javax.swing.JButton();
        checkReceberDinheiro = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelDiarista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de usuário diarista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        txtNome.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtNome.setText("Nome completo *");

        txtPDF.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtPDF.setText("CPF *");

        txtRG.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtRG.setText("RG *");

        txtEndereco.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtEndereco.setText("Endereço *");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Cadastrar conta bancária");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));

        txtHasContaCadastrada.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtHasContaCadastrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHasContaCadastrada.setText("Sem conta cadastrada");

        txtObservacoes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtObservacoes.setText("Observações");

        painelInformacoes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informações sobre as diárias"));

        txtValorDiaria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtValorDiaria.setText("Valor da diária");

        comboValor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        painelDias.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Dias disponíveis"));

        checkSegunda.setText("Segunda");

        checkTerca.setText("Terça");

        checkQuarta.setText("Quarta");

        checkQuinta.setText("Quinta");

        checkSexta.setText("Sexta");

        checkSabado.setText("Sábado");

        checkDomingo.setText("Domingo");

        javax.swing.GroupLayout painelDiasLayout = new javax.swing.GroupLayout(painelDias);
        painelDias.setLayout(painelDiasLayout);
        painelDiasLayout.setHorizontalGroup(
            painelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDiasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDiasLayout.createSequentialGroup()
                        .addGroup(painelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkTerca)
                            .addComponent(checkSegunda))
                        .addGap(75, 75, 75)
                        .addGroup(painelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkSexta)
                            .addComponent(checkQuinta))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDiasLayout.createSequentialGroup()
                        .addComponent(checkQuarta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkDomingo)
                            .addComponent(checkSabado))
                        .addGap(54, 54, 54))))
        );
        painelDiasLayout.setVerticalGroup(
            painelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDiasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSegunda)
                    .addComponent(checkQuinta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkTerca)
                    .addComponent(checkSexta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkQuarta)
                    .addComponent(checkSabado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDomingo))
        );

        javax.swing.GroupLayout painelInformacoesLayout = new javax.swing.GroupLayout(painelInformacoes);
        painelInformacoes.setLayout(painelInformacoesLayout);
        painelInformacoesLayout.setHorizontalGroup(
            painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelInformacoesLayout.createSequentialGroup()
                        .addComponent(txtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(comboValor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelInformacoesLayout.setVerticalGroup(
            painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtValorDiaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboValor))
                .addGap(18, 18, 18)
                .addComponent(painelDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        botaoCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCadastrar.setText("Cadastrar Usuário");
        botaoCadastrar.setBorder(new javax.swing.border.MatteBorder(null));

        txtCamposObrigatorios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCamposObrigatorios.setText("* Estes campos são de preenchimento obrigatório.");

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCancelar.setForeground(new java.awt.Color(153, 0, 51));
        botaoCancelar.setText("Cancelar");
        botaoCancelar.setBorder(new javax.swing.border.MatteBorder(null));

        checkReceberDinheiro.setText("Quero receber em dinheiro");

        javax.swing.GroupLayout painelDiaristaLayout = new javax.swing.GroupLayout(painelDiarista);
        painelDiarista.setLayout(painelDiaristaLayout);
        painelDiaristaLayout.setHorizontalGroup(
            painelDiaristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDiaristaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(painelDiaristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDiaristaLayout.createSequentialGroup()
                        .addComponent(txtCamposObrigatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelDiaristaLayout.createSequentialGroup()
                        .addGroup(painelDiaristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObservacoes)
                            .addComponent(campoObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(179, Short.MAX_VALUE))
                    .addGroup(painelDiaristaLayout.createSequentialGroup()
                        .addGroup(painelDiaristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelDiaristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(checkReceberDinheiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRG, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPDF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHasContaCadastrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelDiaristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelInformacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDiaristaLayout.createSequentialGroup()
                                .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        painelDiaristaLayout.setVerticalGroup(
            painelDiaristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDiaristaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(painelDiaristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDiaristaLayout.createSequentialGroup()
                        .addComponent(txtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(txtRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObservacoes)
                .addGap(2, 2, 2)
                .addComponent(campoObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHasContaCadastrada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDiaristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDiaristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botaoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addComponent(botaoCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelDiaristaLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkReceberDinheiro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(txtCamposObrigatorios))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDiarista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDiarista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoObservacoes;
    private javax.swing.JTextField campoRG;
    private javax.swing.JCheckBox checkDomingo;
    private javax.swing.JCheckBox checkQuarta;
    private javax.swing.JCheckBox checkQuinta;
    private javax.swing.JCheckBox checkReceberDinheiro;
    private javax.swing.JCheckBox checkSabado;
    private javax.swing.JCheckBox checkSegunda;
    private javax.swing.JCheckBox checkSexta;
    private javax.swing.JCheckBox checkTerca;
    private javax.swing.JComboBox<String> comboValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel painelDiarista;
    private javax.swing.JPanel painelDias;
    private javax.swing.JPanel painelInformacoes;
    private javax.swing.JLabel txtCamposObrigatorios;
    private javax.swing.JLabel txtEndereco;
    private javax.swing.JLabel txtHasContaCadastrada;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtObservacoes;
    private javax.swing.JLabel txtPDF;
    private javax.swing.JLabel txtRG;
    private javax.swing.JLabel txtValorDiaria;
    // End of variables declaration//GEN-END:variables
}
