/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.UFSC.INE5608.projetoDiaristas.Telas;

import br.UFSC.INE5608.projetoDiaristas.Controladores.ControladorContratante;

/**
 *
 * @author Ismael
 */
public class TelaCadastroContratante extends javax.swing.JFrame {
    private static TelaCadastroContratante instancia;
    public static TelaCadastroContratante getInstance() {
        if(instancia == null){
            instancia = new TelaCadastroContratante();
        }
        return instancia;
    }
    /**
     * Creates new form TelaCadastroContratante
     */
    private TelaCadastroContratante() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelContratante = new javax.swing.JPanel();
        txtNome = new javax.swing.JLabel();
        txtCPF = new javax.swing.JLabel();
        txtRG = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JLabel();
        botaoCadastraCartao = new javax.swing.JButton();
        txtHasCartaCadastrado = new javax.swing.JLabel();
        campoObservacoes = new javax.swing.JTextField();
        txtObservacoes = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        campoRG = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        painelDadosImovel = new javax.swing.JPanel();
        txtNumeroComodos = new javax.swing.JLabel();
        comboNumeroComodos = new javax.swing.JComboBox<>();
        checkSacada = new javax.swing.JCheckBox();
        checkQuintal = new javax.swing.JCheckBox();
        checkAnivalEstimacao = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        txtCartaoObrigatorio = new javax.swing.JLabel();
        botaoCadastraUsuario = new javax.swing.JButton();
        txtCamposObrigatorios = new javax.swing.JLabel();
        botaoCancela = new javax.swing.JButton();
        campoCPF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelContratante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de usuário contratante de serviço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        txtNome.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtNome.setText("Nome completo *");

        txtCPF.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtCPF.setText("CPF *");

        txtRG.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtRG.setText("RG *");

        txtEndereco.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtEndereco.setText("Endereço *");

        botaoCadastraCartao.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        botaoCadastraCartao.setText("Cadastrar cartão *");
        botaoCadastraCartao.setBorder(new javax.swing.border.MatteBorder(null));
        botaoCadastraCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastraCartaoActionPerformed(evt);
            }
        });

        txtHasCartaCadastrado.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtHasCartaCadastrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHasCartaCadastrado.setText("Sem cartão cadastrado");

        txtObservacoes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtObservacoes.setText("Observações");

        painelDadosImovel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Dados do imóvel"));

        txtNumeroComodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNumeroComodos.setText("* Numero de cômodos:");

        comboNumeroComodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dois cômodos", "Três cômodos", "Quatro cômodos", "Cinco cômodos", "Seis cômodos", "Sete cômodos", "Oito ou mais cômodos" }));
        comboNumeroComodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumeroComodosActionPerformed(evt);
            }
        });

        checkSacada.setText("Possui sacada");
        checkSacada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSacadaActionPerformed(evt);
            }
        });

        checkQuintal.setText("Possui quintal / jardim");
        checkQuintal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkQuintalActionPerformed(evt);
            }
        });

        checkAnivalEstimacao.setText("Possui animal de estimação");
        checkAnivalEstimacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnivalEstimacaoActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Mais alguma coisa");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDadosImovelLayout = new javax.swing.GroupLayout(painelDadosImovel);
        painelDadosImovel.setLayout(painelDadosImovelLayout);
        painelDadosImovelLayout.setHorizontalGroup(
            painelDadosImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosImovelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(painelDadosImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkQuintal)
                    .addComponent(checkSacada)
                    .addComponent(checkAnivalEstimacao)
                    .addComponent(jCheckBox4))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(painelDadosImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNumeroComodos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(comboNumeroComodos, 0, 1, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelDadosImovelLayout.setVerticalGroup(
            painelDadosImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroComodos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumeroComodos))
                .addGap(18, 18, 18)
                .addComponent(checkSacada)
                .addGap(18, 18, 18)
                .addComponent(checkQuintal)
                .addGap(18, 18, 18)
                .addComponent(checkAnivalEstimacao)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox4)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        txtCartaoObrigatorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCartaoObrigatorio.setText("É obrigatório o cadastro de cartão de crédito em nome do usuário.");

        botaoCadastraUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCadastraUsuario.setText("Cadastrar Usuário");
        botaoCadastraUsuario.setBorder(new javax.swing.border.MatteBorder(null));
        botaoCadastraUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastraUsuarioActionPerformed(evt);
            }
        });

        txtCamposObrigatorios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCamposObrigatorios.setText("* Estes campos são de preenchimento obrigatório.");

        botaoCancela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCancela.setForeground(new java.awt.Color(153, 0, 51));
        botaoCancela.setText("Cancelar");
        botaoCancela.setBorder(new javax.swing.border.MatteBorder(null));
        botaoCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelaActionPerformed(evt);
            }
        });

        try {
            campoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout painelContratanteLayout = new javax.swing.GroupLayout(painelContratante);
        painelContratante.setLayout(painelContratanteLayout);
        painelContratanteLayout.setHorizontalGroup(
            painelContratanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelContratanteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(painelContratanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelContratanteLayout.createSequentialGroup()
                        .addComponent(txtCamposObrigatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelContratanteLayout.createSequentialGroup()
                        .addGroup(painelContratanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObservacoes)
                            .addComponent(campoObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelContratanteLayout.createSequentialGroup()
                        .addGroup(painelContratanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelContratanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtRG)
                                .addComponent(txtCPF)
                                .addComponent(txtNome)
                                .addComponent(txtHasCartaCadastrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoCadastraCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEndereco))
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCartaoObrigatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelContratanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoCPF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(painelContratanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelDadosImovel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelContratanteLayout.createSequentialGroup()
                                .addComponent(botaoCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoCadastraUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        painelContratanteLayout.setVerticalGroup(
            painelContratanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelContratanteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(painelContratanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelContratanteLayout.createSequentialGroup()
                        .addComponent(txtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelDadosImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtObservacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHasCartaCadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelContratanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelContratanteLayout.createSequentialGroup()
                        .addComponent(botaoCadastraCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCartaoObrigatorio))
                    .addComponent(botaoCancela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadastraUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCamposObrigatorios))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelContratante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelContratante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkSacadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSacadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSacadaActionPerformed

    private void checkQuintalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkQuintalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkQuintalActionPerformed

    private void checkAnivalEstimacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnivalEstimacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAnivalEstimacaoActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void comboNumeroComodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumeroComodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNumeroComodosActionPerformed

    private void botaoCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelaActionPerformed
        ControladorContratante.getInstance().abreTelaInicial();
        dispose();
    }//GEN-LAST:event_botaoCancelaActionPerformed

    private void botaoCadastraUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastraUsuarioActionPerformed
        //colocar codigo para cadastrar usuário
        
        String cpfTemp = campoCPF.getText();
        cpfTemp = cpfTemp.replace( " " , ""); //tira espaço em branco
        cpfTemp = cpfTemp.replace( "." , ""); //tira ponto
        cpfTemp = cpfTemp.replace( "/" , ""); //tira barra
        cpfTemp = cpfTemp.replace( "-" , ""); //tira hífen
        
        System.out.println(campoCPF.getText());
        System.out.println(cpfTemp);
        Integer cpf = Integer.parseInt(cpfTemp);
        System.out.println(cpf);
        Integer rg = Integer.parseInt(campoRG.getText());       
        //int numComodos = Integer.parseInt(comboNumeroComodos.getSelectedItem().toString());   
                 
        ControladorContratante.getInstance().cadastrarContratante(
            cpf,
            rg, 
            campoNome.getText(), 
            campoEndereco.getText(),
            campoObservacoes.getText(), 
            2,
            //numComodos, 
            checkQuintal.isSelected(),
            checkSacada.isSelected(), 
            checkAnivalEstimacao.isSelected(), 
            jCheckBox4.isSelected()  
        
        );
        
        
    }//GEN-LAST:event_botaoCadastraUsuarioActionPerformed

    private void botaoCadastraCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastraCartaoActionPerformed
        ControladorContratante.getInstance().abreTelaCartao();
    }//GEN-LAST:event_botaoCadastraCartaoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastraCartao;
    private javax.swing.JButton botaoCadastraUsuario;
    private javax.swing.JButton botaoCancela;
    private javax.swing.JFormattedTextField campoCPF;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoObservacoes;
    private javax.swing.JTextField campoRG;
    private javax.swing.JCheckBox checkAnivalEstimacao;
    private javax.swing.JCheckBox checkQuintal;
    private javax.swing.JCheckBox checkSacada;
    private javax.swing.JComboBox<String> comboNumeroComodos;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JPanel painelContratante;
    private javax.swing.JPanel painelDadosImovel;
    private javax.swing.JLabel txtCPF;
    private javax.swing.JLabel txtCamposObrigatorios;
    private javax.swing.JLabel txtCartaoObrigatorio;
    private javax.swing.JLabel txtEndereco;
    private javax.swing.JLabel txtHasCartaCadastrado;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtNumeroComodos;
    private javax.swing.JLabel txtObservacoes;
    private javax.swing.JLabel txtRG;
    // End of variables declaration//GEN-END:variables
}
